### ISSUE TITLE
Conversions of the egor object (network/ igraph)

### ISSUE THREAD

**Issue by tilltnet** [tilltnet/egor#12]
Continuing the discussion in #6, there are at least three ways an egor object could be conversed into objects of the igraph or network packages:

1. Create network/igraph object for each ego-network containing only alters. Output: list of igraphs/networks
2. Create network/igraph object for each ego-network containing egos and alters. Output: list of igraphs/networks
3. Joining all the ego-networks together in one object, containing egos and alters. Output: one network/igraph object

the proposed functions (to_network/ to_igraph [commit](https://github.com/tilltnet/egor/commit/97984e4d6524ccd44319f5f1d6527a591ef227dc)) accomplish  1. and 2.

Concerning 3., according to @mbojan
> Unless multiple people report on the same piece of reality (e.g. two egos reporting on the same alter), IMHO this is a useful data format to have.

Until now, I only heard of joining ego networks together in cases where the egos reported on the same group of people and the researcher is trying to create whole network of said population. Even if the purpose we see in joining the networks are kind of contradictory I feel like this goes to show, that it is useful to have a function for that and it is up to the researcher to decide how and if to use this. Joining ego networks comes along with its own set of problems/questions, but ultimately I think this would be nice to have in the package.

As for the **naming** of these functions I went with to_... instead of methods for as., since including ego is done with additional params, that need some explanation. Also with an as.(method) design I would expect these functions to return an object of the henceforth package, but what they actually return are lists of those objects, so that might be confusing. I am very open to discuss these aspects and adopt another naming scheme or switch to as.(methods). A kind of pythonic way of naming these functions could be to_networks/ to_igraphs, with the plural 's' indicating, that lists of objects are returned.

For 3. I would suggest introducing another function that makes use of the verb 'join'. Maybe join_egos. Or join_ego_networks.

**Comment by mbojan** [comment]
Thanks @tilltnet for gathering it all here.

What's the usecase for (1)?

Object (2) would be very useful to `[l/s]apply` some descriptives to all egonetworks in one go. In fact, there is `sna::gapply` which is very useful. I think it is a legacy code though from the pre-`network` times. It would be nice to have in `network` an analogue to `igraph::make_ego_graph`. `network::get.neighborhood` does something similar to `igraph::ego` already.

As for (3), standby for some examples.

As for the naming, I think I am for implementing methods for `as.network` and `as.igraph` instead of introducing new functions with different names that do essentially the same. It may seem somewhat strange that `as.network` might not return a `network` but a list of thereof, but I don't think that is really a problem. `igraph::as_data_frame` for `what="both"` also returns a list of two data frames. Perhaps it is just a matter of explicit documentation. 

Another possibility: The `ergm` package has a `network.list` class for storing lists of networks (samples from a fitted ERGM). It was created for a specific purpose in mind and `simulate.ergm` stores additional model-related metadata as attributes, but beyond that it is just a list of network objects. AFAIK there are only `print` and `summary` methods for `network.list` objects. Perhaps cases (1) and (2) could be handled by something like `as.network.list`?

In general, and including the infamous `_` vs `.` discussion, I am on a side that sees value in integrating into existing infrastructure rather than 

- introducing new functions that do what you expect from existing generics (like the case of `as_data_frame` in igraph).
- breaking existing R conventions with new syntax without thinking at least twice. This is the case of `as.*` functions for coercion (and `as` S4 generic for that matter), rather than Pythonesque `to_*`.

**Comment by mbojan** [comment]
My last comments above are clearly an opinion, but I have to say that while teaching R frequently to newbies, such inconsistencies are a sore thumb..... Perhaps I'm oversensitive ;)

**Comment by tilltnet** [comment]
Haha :) "Thinking twice" - that sounds like a big waste of time! ;)

Seriously: I think we can avoid having that "big" discussion on here and just make practical decisions. I'm happy to learn from you experience though, so feel free to share your opinions!

>What's the usecase for (1)?

When visualising ego centered networks, in many cases ego only adds 'noise' to the plot since ego is connected to everybody. Same goes for some measures. Also some people like to compare ego network plots with ego to plots without ego.

From your post I like the version of doing it all with `as.network/as.igraph` functions more, the output of `as.network`, could be a `network.list `still, I guess.

So the functions could look something like this:

`as.network.egor <- function(x, mode = c("wo.ego", "w.ego", "join"), ego.attrs = NULL, ego.alts.attrs = NULL) ...
`
ego.attrs & ego.alts.attrs would allow to specify the variables to be used for vertex and edge attributes. If unspecified all available variables would be used. Do the param names make sense or are there better suggestions?

About the "join" mode. How would you expect that to work? Should alters with the same name from different egos assumed to be the same person? What about the egos? An ego could be an alter in anothers egos network. So the egos would need to have a 'name' attribute as well.

**Comment by tilltnet** [comment]
The conversion functions are now named:

- as_network()
- as_igraph()

Both return lists of igraph/network objects.

Aliases of these functions are S3 methods for as.network and as.igraph. So when the user has i.e. network loaded as.network() works as well. I feel this way the documentation can be most explicit.

This is still open: feature to join all networks in one network/igraph object, two useful modes:

1. Merge: same names/IDs for egos and alters are treated as the same person. (when both are collected for one person ego attributes should probably supersede alter attributes)
2. Join: names/ IDs are modified in order to keep networks separated clusters. (egoID as prefix for alter, egoID_ego_.

**Comment by tilltnet** [comment]
converting to network or igraph now also allows to include ego variables as network/graph attributes instead of node attributes.

Todo: add conversion from igraph/ network to egor.
