### ISSUE TITLE
Switch all optional arguments from if(!is.null(x)) to if(missing(x))

### ISSUE THREAD

**Issue by tilltnet** [tilltnet/egor#25]
Cleans up documentation, since argument definition of 'x = NULL' becomes 'x'.

**Comment by krivit** [comment]
Is this a good idea outside of things like indexing operations? I've found that using `NULL` makes it easier to call the function from another function, since you can change their behavior without using a different call.

**Comment by tilltnet** [comment]
> change their behavior without using a different call

What do you mean by this? Can you give an example?

**Comment by krivit** [comment]
Suppose that I want a function that takes one or two numeric vectors, transforms them, and evaluates a one- or two-sample t test depending on how many numeric vectors were passed.

`stats:::t.test.default` has `NULL` as the default value for its second argument, performing a one-sample test, and so my function would only need one call to `t.test` for both modes of operation, rather than having to dispatch conditionally.

**Comment by mbojan** [comment]
I second @krivit 's point. `missing()` leads to functions that are cumbersome to use if you need to call them repeatedly with some of the arguments missing from time to time. Passing `NULL` (or sth else) is easier than layers of `if()`s or `do.call()` acrobatics.

**Comment by tilltnet** [comment]
Thanks to both of you @krivit , @mbojan . I wasn't aware of that! I read a bit about it and there is also the argument, that the 'argument = NULL' variant makes it more apparent which variables are optional. I guess we keep it as it is right now.
