### ISSUE TITLE
problems after up date to latest version

### ISSUE THREAD

**Issue by Ngaoundere-Egos** [tilltnet/egor#34]
There are several problems after I updated yesterday. My original egor object doesn't seem to function any longer? 
 
1) egor_vis_app(egor_obj)
**Error in tag("div", list(...)) : argument is missing, with no default**
2)
 ECN <- as_igraph(egor_obj, directed = FALSE, include.ego = TRUE, ego.attrs = NULL, ego.alter.weights = NULL)
Error in UseMethod("select_") : 
  n**o applicable method for 'select_' applied to an object of class "NULL"**
In addition: Warning message:
Unknown or uninitialised column: ### 'aatie'.

**Comment by tilltnet** [comment]
Hi thank you so much for your feedback.

With ego version 0.19.10 (published in november 2019) changes to the egor object were introduced, that are not compatible with prior egor versions.

In case your egor object was created with a version before 0.19.10, you'll have to transform the old object. 

The code below converts an old egor object to a new one. In the first three commands, substitute `old_egor_obj` with the name of you object. In the `egor()` call make sure that the id variable names are correct. You might get a warning about reserved variable names - that should not be a real problem here though, so just ignore.

 ```
 alts <- old_egor_obj %>%
    select(.egoID, .alts) %>%
    tidyr::unnest(.alts)
  
aaties <- old_egor_obj %>%
    select(.egoID, .aaties) %>%
    tidyr::unnest(.aaties)
  
egos <- old_egor_obj %>%
    select(-.alts, -.aaties)
  
new_egor_obj <- egor(
    alts,
    egos,
    aaties,
    ID.vars = list(
      ego = ".egoID",
      alter = ".altID",
      source = ".srcID",
      target = ".tgtID"
    )
  )
```

Let me know if this works for you and please take a look at the [updated vignette](http://egor.tillt.net/articles/using_egor.html), to learn about new features.

You can also contact me at egor@tillt.net

**Comment by tilltnet** [comment]
The development version now has a command to converts nested_egor objects or egor objects created before egor version 0.19.10 to an egor object that works with the current versions of the package.

When using it with an old egor object the following code should work:

```
class(egor_obj) <- "nested_egor"
as.egor(egor_obj)
```

**Comment by tilltnet** [comment]
This solution now also works with egor version 0.20.06 that was released on CRAN today
