### ISSUE TITLE
Representing directed relations

### ISSUE THREAD

**Issue by krivit** [tilltnet/egor#9]
As @tilltnet pointed out to me a while ago, directed relations in egocentric data are produced by paired name generators:
* 'Name people that you receive emotional support from' (in-tie)
* 'Name people that you give emotional support to' (out-tie)

In an alter-alter matrix, directionality is easily formalized by specifying source and the target; but what about the ego-alter nominations? We may want to standardize this in a way that allows similar types of relations to be observed on alters and alter-alter relations and for the software to be aware that they are linked.

# Proposal #

So far, the best way I can think of is by combining the directions of a directed relationship into a list with two named elements, say, `in` and `out`, so, for example, if there is an alter attribute `emo_support` (and assuming other names for things don't change), something like
```
subset(egor, .alters$emo_support$in & .alters$emo_support$out, aspect="alters")
```
would select only those alters with whom the ego has mutual emotional support, while
```
subset(egor, (!.alters$emo_support$in) & .alters$emo_support$out, aspect="alters")
```
would select those alters whom ego supports but is not supported by.

This approach might require changes to the importing and reading functions, since they would need to be passed information about what columns in the data to pair off.

# Alter-alter matrix #

A related issue is how we specify whether a particular alter-alter relation is directed or not. I am not sure whether there is a great way to do that.

**Comment by tilltnet** [comment]
I am torn about this one. I think pushing the actual data down one level is problematic and potentially confusing. It makes it harder for the user to insepect the data. If we go on with the way it is right now, your second example could look like this:

'subset(egor, (!.alters$emo_support_in) & .alters$emo_support_out, aspect="alters")'

A part from the fact that handlich in- and outgoing reltions is feasible with the current data strucutre, something else I am thinking about here: a lot of the studies I worked with, would use only incoming relationships in the name generators, since ego centered network analysis is often used in studies on social support and the alters are regarded as intermediaries to ressources. Therefore I don't see the gain in changing this for all cases. Having the option to handle in/out relations the way you describe would be nice for the (I claim, small,) group of studies that make use of it, but making the egor object less accesible for erveryone doesn't feel right to me.

As long as alter-alter relations are stored as edgelists there are the Source and Target columns. This allows us to either ignore the direction (undirected data) or make us of it (directed data), when we conduct the analysis. So all analysis functions should be able to switch from directed to undirecetd. If we want to store that information in the egor object I propose an attribute for that or including it in the study design attribute.

**Comment by krivit** [comment]
OK, it's less elegant, IMO, but I can live with that. It's consistent with the philosophy that the purpose of the `egor` object is to store the data as collected, not its interpretation by a particular researcher.

**Comment by tilltnet** [comment]
I'm absolutly open to reevaluating this at a later point, if it turns out to be more common to collect in- and outgoing ego-alter ties or users request it as a feature.
